---
abstract: 'Sugar for the params() keyword'
author:
  - 'Chris Tijerina'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.037, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dancer2-Plugin-ParamShortcuts
provides: {}
requires:
  Dancer2::Plugin: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/Camspi/Dancer2-Plugin-ParamShortcuts/issues
  homepage: https://github.com/Camspi/Dancer2-Plugin-ParamShortcuts
  repository: https://github.com/Camspi/Dancer2-Plugin-ParamShortcuts.git
version: v0.0.1
